@host=Http://localhost:5000

POST {{host}}/auth/register
Content-Type: application/json

{
	"username":"ggg1",
	"firstName":"George",
	"lastName":"Darchiashvili",
	"email":"George1@Darchiashvili.com",
	"password":"George123"
}